/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAdminSystemsRouteImport } from './routes/dashboard/admin/systems'
import { Route as DashboardAdminSectionsRouteImport } from './routes/dashboard/admin/sections'
import { Route as DashboardAdminRolesRouteImport } from './routes/dashboard/admin/roles'
import { Route as DashboardAdminProfilesRouteImport } from './routes/dashboard/admin/profiles'
import { Route as DashboardAdminDivisionsRouteImport } from './routes/dashboard/admin/divisions'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminSystemsRoute = DashboardAdminSystemsRouteImport.update({
  id: '/admin/systems',
  path: '/admin/systems',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminSectionsRoute = DashboardAdminSectionsRouteImport.update({
  id: '/admin/sections',
  path: '/admin/sections',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRolesRoute = DashboardAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminProfilesRoute = DashboardAdminProfilesRouteImport.update({
  id: '/admin/profiles',
  path: '/admin/profiles',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminDivisionsRoute = DashboardAdminDivisionsRouteImport.update({
  id: '/admin/divisions',
  path: '/admin/divisions',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/divisions': typeof DashboardAdminDivisionsRoute
  '/dashboard/admin/profiles': typeof DashboardAdminProfilesRoute
  '/dashboard/admin/roles': typeof DashboardAdminRolesRoute
  '/dashboard/admin/sections': typeof DashboardAdminSectionsRoute
  '/dashboard/admin/systems': typeof DashboardAdminSystemsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/admin/divisions': typeof DashboardAdminDivisionsRoute
  '/dashboard/admin/profiles': typeof DashboardAdminProfilesRoute
  '/dashboard/admin/roles': typeof DashboardAdminRolesRoute
  '/dashboard/admin/sections': typeof DashboardAdminSectionsRoute
  '/dashboard/admin/systems': typeof DashboardAdminSystemsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/divisions': typeof DashboardAdminDivisionsRoute
  '/dashboard/admin/profiles': typeof DashboardAdminProfilesRoute
  '/dashboard/admin/roles': typeof DashboardAdminRolesRoute
  '/dashboard/admin/sections': typeof DashboardAdminSectionsRoute
  '/dashboard/admin/systems': typeof DashboardAdminSystemsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/admin/divisions'
    | '/dashboard/admin/profiles'
    | '/dashboard/admin/roles'
    | '/dashboard/admin/sections'
    | '/dashboard/admin/systems'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboard/admin/divisions'
    | '/dashboard/admin/profiles'
    | '/dashboard/admin/roles'
    | '/dashboard/admin/sections'
    | '/dashboard/admin/systems'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/admin/divisions'
    | '/dashboard/admin/profiles'
    | '/dashboard/admin/roles'
    | '/dashboard/admin/sections'
    | '/dashboard/admin/systems'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/systems': {
      id: '/dashboard/admin/systems'
      path: '/admin/systems'
      fullPath: '/dashboard/admin/systems'
      preLoaderRoute: typeof DashboardAdminSystemsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/sections': {
      id: '/dashboard/admin/sections'
      path: '/admin/sections'
      fullPath: '/dashboard/admin/sections'
      preLoaderRoute: typeof DashboardAdminSectionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/roles': {
      id: '/dashboard/admin/roles'
      path: '/admin/roles'
      fullPath: '/dashboard/admin/roles'
      preLoaderRoute: typeof DashboardAdminRolesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/profiles': {
      id: '/dashboard/admin/profiles'
      path: '/admin/profiles'
      fullPath: '/dashboard/admin/profiles'
      preLoaderRoute: typeof DashboardAdminProfilesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/divisions': {
      id: '/dashboard/admin/divisions'
      path: '/admin/divisions'
      fullPath: '/dashboard/admin/divisions'
      preLoaderRoute: typeof DashboardAdminDivisionsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAdminDivisionsRoute: typeof DashboardAdminDivisionsRoute
  DashboardAdminProfilesRoute: typeof DashboardAdminProfilesRoute
  DashboardAdminRolesRoute: typeof DashboardAdminRolesRoute
  DashboardAdminSectionsRoute: typeof DashboardAdminSectionsRoute
  DashboardAdminSystemsRoute: typeof DashboardAdminSystemsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAdminDivisionsRoute: DashboardAdminDivisionsRoute,
  DashboardAdminProfilesRoute: DashboardAdminProfilesRoute,
  DashboardAdminRolesRoute: DashboardAdminRolesRoute,
  DashboardAdminSectionsRoute: DashboardAdminSectionsRoute,
  DashboardAdminSystemsRoute: DashboardAdminSystemsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
